version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db1
      - db2
    environment:
      # 이제 DB1은 TermCompass 데이터베이스 (포트 3306)
      DB1_HOST: db1
      DB1_PORT: 3306
      DB1_USER: termcompass
      DB1_PASSWORD: termcompass
      DB1_NAME: TermCompass
      # DB2는 termcompass_law 데이터베이스 (포트 9907)
      DB2_HOST: db2
      DB2_PORT: 3307
      DB2_USER: termcompass
      DB2_PASSWORD: termcompass
      DB2_NAME: termcompass_law

  db1:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: TermCompass
      MYSQL_USER: termcompass
      MYSQL_PASSWORD: termcompass

  db2:
    image: mysql:8.0
    ports:
      - "3307:3306"  # 컨테이너 내부의 MySQL은 기본 포트 3306입니다.
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: termcompass_law
      MYSQL_USER: termcompass
      MYSQL_PASSWORD: termcompass
